apiVersion : apps/v1
kind: Deployment
metadata:
  name: hewisauruspipelinesjavascriptdockerr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hewisauruspipelinesjavascriptdockerr
  template:
    metadata:
      labels:
        app: hewisauruspipelinesjavascriptdockerr
    spec:
      containers:
        - name: hewisauruspipelinesjavascriptdockerr
          image: xelloakscicdacr.azurecr.io/hewisauruspipelinesjavascriptdocker
          ports:
          - containerPort: 8080
